.\" man page for ffetch
.TH ffetch 1 "March 2022" "jornmann" "Fetch Script"

.SH NAME
.P
ffetch - simple but pretty fetch script

.SH SYNOPSIS
.P
ffetch
.P
arg="[nologo | nofetch]" ffetch

.SH DESCRIPTION
.P
ffetch is a utility that gathers and shows information about your system.

.SH OPTIONS
.P
ffetch is configured with ~/.ffetchrc or by setting variables before running. See the SYNOPSIS for an example of this.

.SH BUGS
.P
Probably lots. If you find one, don't be afraid to contact me: <jornmann at duck dot com>
