.\" man page for zfetch
.TH zfetch 1 "March 2022" "github.com/jornmann/zfetch" "Fetch Script"

.SH NAME
.P
zfetch - simple but pretty fetch script

.SH SYNOPSIS
.P
zfetch
.P
arg="[nologo | nofetch]" zfetch

.SH DESCRIPTION
.P
zfetch is a utility that gathers and shows information about your system.

.SH OPTIONS
.P
zfetch is configured with ~/.zfetchrc or by setting variables before running. See the SYNOPSIS for an example of this.

.SH BUGS
.P
Probably lots. If you find one, don't be afraid to contact me: <jornmann at duck dot com>
